// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config"

// Only load .env files if DATABASE_URL is not already set (e.g., in CI with dummy values)
if (!process.env.DATABASE_URL) {
  try {
    const { config } = require("dotenv")
    config({ path: ".env.local" })
    config({ path: ".env" })
  } catch (e) {
    // dotenv not available, continue without it
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
})
