// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig } from "prisma/config"

// Load environment variables - try .env.local first, then .env
try {
  const { config } = require("dotenv")
  config({ path: ".env.local" })
  config({ path: ".env" })
} catch (e) {
  // dotenv already imported via 'dotenv/config'
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
})
